export const mockUpList = [
  {
    images: [`/images/bg-landing-page.png`, `/images/background-image.jpg`],
    price: 3000000,
    propertyName: "Luxury Villa Ubud",
    landSize: 300,
    buildSize: 400,
    location: "Ubud, Bali",
    bathRoom: 3,
    bedRoom: 5,
  },
  {
    images: [`/images/bg-landing-page.png`, `/images/background-image.jpg`],
    price: 3000000,
    propertyName: "Luxury Villa Ubud",
    landSize: 300,
    buildSize: 400,
    location: "Ubud, Bali",
    bathRoom: 3,
    bedRoom: 5,
  },
  {
    images: [`/images/bg-landing-page.png`, `/images/background-image.jpg`],
    price: 3000000,
    propertyName: "Luxury Villa Ubud",
    landSize: 300,
    buildSize: 400,
    location: "Ubud, Bali",
    bathRoom: 3,
    bedRoom: 5,
  },
  {
    images: [`/images/bg-landing-page.png`, `/images/background-image.jpg`],
    price: 3000000,
    propertyName: "Luxury Villa Ubud",
    landSize: 300,
    buildSize: 400,
    location: "Ubud, Bali",
    bathRoom: 3,
    bedRoom: 5,
  },
  {
    images: [`/images/bg-landing-page.png`, `/images/background-image.jpg`],
    price: 3000000,
    propertyName: "Luxury Villa Ubud",
    landSize: 300,
    buildSize: 400,
    location: "Ubud, Bali",
    bathRoom: 3,
    bedRoom: 5,
  },
  {
    images: [`/images/bg-landing-page.png`, `/images/background-image.jpg`],
    price: 3000000,
    propertyName: "Luxury Villa Ubud",
    landSize: 300,
    buildSize: 400,
    location: "Ubud, Bali",
    bathRoom: 3,
    bedRoom: 5,
  },
  {
    images: [`/images/bg-landing-page.png`, `/images/background-image.jpg`],
    price: 3000000,
    propertyName: "Luxury Villa Ubud",
    landSize: 300,
    buildSize: 400,
    location: "Ubud, Bali",
    bathRoom: 3,
    bedRoom: 5,
  },
  {
    images: [`/images/bg-landing-page.png`, `/images/background-image.jpg`],
    price: 3000000,
    propertyName: "Luxury Villa Ubud",
    landSize: 300,
    buildSize: 400,
    location: "Ubud, Bali",
    bathRoom: 3,
    bedRoom: 5,
  },
  {
    images: [`/images/bg-landing-page.png`, `/images/background-image.jpg`],
    price: 3000000,
    propertyName: "Luxury Villa Ubud",
    landSize: 300,
    buildSize: 400,
    location: "Ubud, Bali",
    bathRoom: 3,
    bedRoom: 5,
  },
  {
    images: [`/images/bg-landing-page.png`, `/images/background-image.jpg`],
    price: 3000000,
    propertyName: "Luxury Villa Ubud",
    landSize: 300,
    buildSize: 400,
    location: "Ubud, Bali",
    bathRoom: 3,
    bedRoom: 5,
  },
  {
    images: [`/images/bg-landing-page.png`, `/images/background-image.jpg`],
    price: 3000000,
    propertyName: "Luxury Villa Ubud",
    landSize: 300,
    buildSize: 400,
    location: "Ubud, Bali",
    bathRoom: 3,
    bedRoom: 5,
  },
  {
    images: [`/images/bg-landing-page.png`, `/images/background-image.jpg`],
    price: 3000000,
    propertyName: "Luxury Villa Ubud",
    landSize: 300,
    buildSize: 400,
    location: "Ubud, Bali",
    bathRoom: 3,
    bedRoom: 5,
  },
];
