import type { Metadata } from "next";
import { Inter, Josefin_Sans, Lato, Montserrat } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Layout/Navbar";
import Footer from "@/components/Layout/Footer";
import { NextIntlClientProvider, useMessages } from "next-intl";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const josefin_sans = Josefin_Sans({
  subsets: ["latin"],
  variable: "--font-josefin_sans",
});
const lato = Lato({
  subsets: ["latin"],
  variable: "--font-lato",
  weight: ["100", "300", "400", "700", "900"],
});
const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});
const audrey = localFont({
  src: [
    {
      path: "/fonts/Audrey/Audrey-Normal.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "/fonts/Audrey/Audrey-Medium.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "/fonts/Audrey/Audrey-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-audrey",
});

export const metadata: Metadata = {
  title: "Sela Property",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const message = useMessages();
  return (
    <html lang={locale}>
      <NextIntlClientProvider messages={message}>
        <body
          className={`${inter.className} ${audrey.variable} ${josefin_sans.variable} ${lato.className} ${montserrat.variable}`}
        >
          <Navbar />
          {children}
          <Footer />
        </body>
      </NextIntlClientProvider>
    </html>
  );
}
